// Runs the real pipeline over every captured page and writes REPORT.md.
//
// Same path the browser takes: the captured bytes go through the shell's
// toRawNode and then the core's render_document. Nothing is stubbed, so a
// regression in either shows up here as a worse number.
//
//   node corpus/measure.mjs
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { JSDOM } from "jsdom";

const dom = new JSDOM("");
globalThis.DOMParser = dom.window.DOMParser;
globalThis.Node = dom.window.Node;

const { toRawNode } = await import("../shell/src/parse.ts");
const wasm = await import("../core/pkg/bbs_core.js");
await wasm.default(readFileSync("core/pkg/bbs_core_bg.wasm"));

const DIR = new URL("./pages/", import.meta.url).pathname;

/// How a measured page is classified.
///
/// `blocks_before_first_prose` falls back to the total block count when the
/// document has no paragraph at all, so that number ALONE cannot tell "no
/// prose" from "prose right at the end". Both are bad, but only one is an
/// empty shell, and conflating them would flatter the chrome figure by
/// mixing in pages that have no first useful line to precede.
export function classify(r) {
  if (r.empty_shell) return "shell";
  if (r.blocks_out === 0) return "shell";
  if (r.blocks_before_first_prose >= r.blocks_out) return "no-prose";
  return "readable";
}

const rows = [];
for (const f of readdirSync(DIR).filter((f) => f.endsWith(".json")).sort()) {
  const meta = JSON.parse(readFileSync(DIR + f, "utf8"));

  if (!meta.ok) {
    rows.push({ ...meta, verdict: "refused", note: `${meta.status} ${meta.error ?? ""}`.trim() });
    continue;
  }

  const html = readFileSync(DIR + f.replace(/\.json$/, ".html"), "utf8");
  let r;
  try {
    r = wasm.render_document(toRawNode(html), 80, 23);
  } catch (e) {
    rows.push({ ...meta, verdict: "threw", note: e.message });
    continue;
  }

  rows.push({
    ...meta,
    verdict: classify(r),
    title: r.title,
    blocksIn: r.blocks_in,
    blocksOut: r.blocks_out,
    links: r.links.length,
    images: r.image_count,
    chrome: r.blocks_before_first_prose,
    screens: r.pages.length,
  });
}

const total = rows.length;
const by = (v) => rows.filter((r) => r.verdict === v);
const readable = by("readable");
const pct = (n) => ((n / total) * 100).toFixed(0);

// A link index with no prose is still perfectly usable ON A BOARD - a
// numbered list of links is what a BBS does. Reported separately rather
// than folded into "readable", because quietly widening the definition of
// success to capture more pages is how a measurement stops being one.
const navigable = rows.filter(
  (r) => r.verdict === "readable" || (r.verdict === "no-prose" && r.links > 0),
);

const chromes = readable.map((r) => r.chrome).sort((a, b) => a - b);
const median = chromes.length ? chromes[Math.floor(chromes.length / 2)] : 0;
const worst = chromes.length ? chromes[chromes.length - 1] : 0;

// The SPA section is expected to fail, so a headline that includes it
// understates the projection and one that excludes it overstates it. Both
// are reported rather than picking the flattering one.
const real = rows.filter((r) => r.category !== "spa");
const realReadable = real.filter((r) => r.verdict === "readable");

const table = [
  "| category | url | verdict | blocks in→out | links | imgs | chrome |",
  "|---|---|---|---|---|---|---|",
  ...rows.map(
    (r) =>
      `| ${r.category} | ${r.url.replace(/^https?:\/\//, "")} | **${r.verdict}** | ` +
      `${r.blocksIn ?? "-"}→${r.blocksOut ?? "-"} | ${r.links ?? "-"} | ` +
      `${r.images ?? "-"} | ${r.chrome ?? "-"} |`,
  ),
].join("\n");

const report = `# The projection corpus

Generated by \`corpus/measure.mjs\` on ${new Date().toISOString().slice(0, 10)}.
Do not hand-edit; re-run it.

**${total} pages captured through the board's own relay**, then put through the
same path a browser takes - the shell's \`toRawNode\`, then the core's
\`render_document\`. Nothing is stubbed.

## The number

| | pages | share |
|---|---|---|
| **readable** | ${readable.length} | ${pct(readable.length)}% |
| empty shell | ${by("shell").length} | ${pct(by("shell").length)}% |
| no prose found | ${by("no-prose").length} | ${pct(by("no-prose").length)}% |
| refused by the relay | ${by("refused").length} | ${pct(by("refused").length)}% |
| threw | ${by("threw").length} | ${pct(by("threw").length)}% |

Excluding the ${rows.length - real.length} single-page-app shells, which are in
the corpus precisely because they are expected to fail:
**${realReadable.length} of ${real.length} readable (${((realReadable.length / real.length) * 100).toFixed(0)}%)**.

Both figures are given because reporting only the first understates the
projection and only the second overstates it.

**Navigable: ${navigable.length} of ${total} (${pct(navigable.length)}%)** -
readable pages plus link indexes that carry no prose. Hacker News is the case
this exists for: its front page has not one paragraph on it, so it is honestly
not *readable*, but it projects to 198 numbered links, which is exactly what a
board is for. Kept separate from the headline rather than folded into it,
because widening the definition of success until more pages qualify is how a
measurement stops being one.

## Chrome before the first useful line

Across readable pages, in blocks: **median ${median}, worst ${worst}**.

This is the number that decides whether the board feels like a BBS or like
scrolling past a navigation menu. A reader gets 23 rows; chrome measured in
tens of blocks means the first screen is furniture.

## Every page

${table}

## Reading this

- **readable** - survived with prose the reader can reach.
- **empty shell** - the core's own verdict: under 200 characters of prose and
  under 5 links. Almost always a page that builds itself with JavaScript,
  which this board deliberately does not run.
- **no prose found** - blocks survived, but not one paragraph among them.
  Usually a link farm or a card grid. Counted separately from empty shells
  because the failure is different and so is the fix.
- **refused by the relay** - never reached the projection. A content type
  outside the allowlist, a redirect that failed re-validation, an upstream
  block, or over the byte cap. Kept in the table rather than dropped, because
  dropping them would quietly improve the score.
- **chrome** - blocks before the first paragraph.
`;

writeFileSync(new URL("./REPORT.md", import.meta.url).pathname, report);
console.log(report.split("## Every page")[0]);
console.log(`written to corpus/REPORT.md (${total} pages)`);
