/// CP437 8x16 bitmap font. 256 glyphs, 16 rows each, one byte per row, MSB
/// leftmost. Generated by `assets/gen_font.py` - edit the generator and
/// regenerate rather than hand-editing these bytes.
pub static FONT: &[u8; 4096] = include_bytes!("../assets/cp437-8x16.bin");

/// CP437 8x8, for the 80x50 mode. Same generator, same code page, half the
/// rows - which is exactly what a VGA card did when it switched modes.
pub static FONT_8X8: &[u8; 2048] = include_bytes!("../assets/cp437-8x8.bin");

/// The ART fonts: the same glyphs, but with the alphabet slots replaced by
/// a sixteen-rung shade ramp.
///
/// CP437 gives the quantiser only three shade densities, so with space and
/// the full block it has a five-rung tonal ladder to represent a continuous
/// image on - the coarsest link in the pipeline. XBIN's custom-font feature
/// exists for exactly this, and a photograph contains no letters, so those
/// slots are free.
pub static ART_FONT_8X16: &[u8; 4096] = include_bytes!("../assets/cp437-art-8x16.bin");
pub static ART_FONT_8X8: &[u8; 2048] = include_bytes!("../assets/cp437-art-8x8.bin");

/// Slots carrying the extra ramp. Must match ART_SLOTS in gen_font.py.
pub const ART_SHADES: std::ops::RangeInclusive<u8> = 0x41..=0x50;

/// The font for a given cell height. 8 and 16 are the two real VGA text
/// modes; anything else falls back to 8x16 rather than inventing a font.
pub fn font_for(cell_h: u32) -> &'static [u8] {
    if cell_h == 8 {
        FONT_8X8.as_slice()
    } else {
        FONT.as_slice()
    }
}

/// As font_for, but the art variant with the finer shade ramp.
pub fn art_font_for(cell_h: u32) -> &'static [u8] {
    if cell_h == 8 {
        ART_FONT_8X8.as_slice()
    } else {
        ART_FONT_8X16.as_slice()
    }
}

/// The glyph mask at a given cell height, packed from the top so bit 127 is
/// always the top-left pixel regardless of height. An 8-row glyph therefore
/// occupies bits 127..64 and leaves the rest clear, which keeps the XOR and
/// popcount comparison in choose_glyph identical for both modes.
pub fn glyph_mask_h(code: u8, cell_h: u32) -> u128 {
    glyph_mask_in(font_for(cell_h), code, cell_h)
}

/// The mask from a specific font, so the art font can be searched without
/// swapping the one the board draws text with.
pub fn glyph_mask_in(font: &[u8], code: u8, cell_h: u32) -> u128 {
    let h = cell_h as usize;
    let start = (code as usize) * h;
    let mut m: u128 = 0;
    for i in 0..h {
        m |= (font[start + i] as u128) << (120 - i * 8);
    }
    m
}

pub fn glyph(code: u8) -> &'static [u8; 16] {
    let start = (code as usize) * 16;
    FONT[start..start + 16].try_into().unwrap()
}

/// The glyph as a 128-bit mask, row-major, bit 127 is the top-left pixel.
/// Packing it this way turns shape comparison into one XOR and one popcount.
pub fn glyph_mask(code: u8) -> u128 {
    let g = glyph(code);
    let mut m: u128 = 0;
    for (i, &row) in g.iter().enumerate() {
        m |= (row as u128) << (120 - i * 8);
    }
    m
}

/// The glyphs the quantiser is allowed to choose from.
///
/// Deliberately not all 256. Letters and punctuation make photographs look
/// like ransom notes, and searching the full font costs twice as much for
/// worse output. This is the block, shade and line-drawing subset BBS
/// artists used, plus a few marks that genuinely help at small scale.
pub const CANDIDATES: &[u8] = &[
    0x20, // space
    0xB0, 0xB1, 0xB2, // light, medium, dark shade
    0xDB, // full block
    0xDC, 0xDD, 0xDE, 0xDF, // lower, left, right, upper half
    0xB3, 0xB4, 0xB9, 0xBA, 0xBB, 0xBC, 0xBF, // box drawing
    0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xD9,
    0xDA, //
    0xFE, // small centred square
    0x2E, 0x3A, 0x2D, 0x7C, 0x2B, 0x2F, 0x5C, // . : - | + / \
];

/// Precomputed masks for the candidate set, in the same order.
pub fn candidate_masks() -> Vec<(u8, u128)> {
    CANDIDATES.iter().map(|&c| (c, glyph_mask(c))).collect()
}
