/// CP437 8x16 bitmap font. 256 glyphs, 16 rows each, one byte per row, MSB
/// leftmost. Generated by `assets/gen_font.py` - edit the generator and
/// regenerate rather than hand-editing these bytes.
pub static FONT: &[u8; 4096] = include_bytes!("../assets/cp437-8x16.bin");

pub fn glyph(code: u8) -> &'static [u8; 16] {
    let start = (code as usize) * 16;
    FONT[start..start + 16].try_into().unwrap()
}

/// The glyph as a 128-bit mask, row-major, bit 127 is the top-left pixel.
/// Packing it this way turns shape comparison into one XOR and one popcount.
pub fn glyph_mask(code: u8) -> u128 {
    let g = glyph(code);
    let mut m: u128 = 0;
    for (i, &row) in g.iter().enumerate() {
        m |= (row as u128) << (120 - i * 8);
    }
    m
}

/// The glyphs the quantiser is allowed to choose from.
///
/// Deliberately not all 256. Letters and punctuation make photographs look
/// like ransom notes, and searching the full font costs twice as much for
/// worse output. This is the block, shade and line-drawing subset BBS
/// artists used, plus a few marks that genuinely help at small scale.
pub const CANDIDATES: &[u8] = &[
    0x20, // space
    0xB0, 0xB1, 0xB2, // light, medium, dark shade
    0xDB, // full block
    0xDC, 0xDD, 0xDE, 0xDF, // lower, left, right, upper half
    0xB3, 0xB4, 0xB9, 0xBA, 0xBB, 0xBC, 0xBF, // box drawing
    0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xD9,
    0xDA, //
    0xFE, // small centred square
    0x2E, 0x3A, 0x2D, 0x7C, 0x2B, 0x2F, 0x5C, // . : - | + / \
];

/// Precomputed masks for the candidate set, in the same order.
pub fn candidate_masks() -> Vec<(u8, u128)> {
    CANDIDATES.iter().map(|&c| (c, glyph_mask(c))).collect()
}
